name: Azure Databricks API Flow

on:
  workflow_dispatch:

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  databricks-job:
    name: Databricks API Flow
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run databricks-api-flow.ps1
        shell: pwsh
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          Write-Host "🚀 Running databricks-api-flow.ps1..."
          & "./scripts/databricks-api-flow.ps1"
