name: Destroy Infrastructure

# Manual trigger only
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run destroy.ps1
        shell: pwsh
        run: |
          Write-Host "🚀 Running destroy.ps1..."
          & "${{ github.workspace }}/scripts/destroy.ps1" -ParametersFile "${{ github.workspace }}/parameters.json"
